server:
  applicationConnectors:
  - type: ${SERVER_APP_CONNECTOR:-http}
    port: ${SERVER_APP_PORT:-9044}
  adminConnectors:
  - type: ${SERVER_ADMIN_CONNECTOR:-http}
    port: ${SERVER_ADMIN_PORT:-9045}

downstreamDataSource: ${DOWNSTREAM_API_URL:-https://bpdts-test-app.herokuapp.com}
cityRadius: ${CITY_DISTANCE_RADIUS:-50}

logging:
  level: ${GLOBAL_LOG_LEVEL:-INFO}
  loggers:
    "uk.gov": ${UK_GOV_LOG_LEVEL:-DEBUG}

